#!/bin/bash
rsync --exclude yarn* --exclude .git --exclude config.php --exclude crawler.log --exclude node_modules -av --del ../* tools:tools

# Copy files
ssh tools <<'ENDSSH'
cp -r tools/* /data/project/hay/
ENDSSH
