#!/bin/bash
if [ $# -eq 0 ]
  then
    echo "deploy-project-test <projectname>"
fi

echo "Building $1"
npm install --prefix ../public_html/$1
npm run --prefix ../public_html/$1 dist

echo "Deploying projectname '$1'"

git rev-parse HEAD > ../public_html/version.txt
rsync --verbose --delay-updates -F --compress --archive --no-owner --no-group --exclude .git --exclude config.php --exclude config-prod.php --exclude crawler.log --exclude node_modules --exclude cache --del --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u tools.hay-test rsync' --chmod=Dug=rwx,Dg+s,Do=rx,Fug=rw,Fo=r ../public_html/$1/ login.toolforge.org:/data/project/hay-test/public_html/$1

say -v Fred "Deploy $1 complete"