FROM php:8.4-apache

RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql
RUN apt update && apt install -y --no-install-recommends git zip unzip

COPY --from=composer:2.9 /usr/bin/composer /usr/bin/composer